version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bank_task_db
      POSTGRES_USER: bank_task_db_user
      POSTGRES_PASSWORD: 123456@bank_task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: